@baseUrl = http://localhost:3001
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImR1Y3RyaTA5ODFAZ21haWwuY29tIiwidXNlcl9pZCI6MSwiaWF0IjoxNzcwNDMxMzA1LCJleHAiOjE3NzA0MzIyMDV9.bUcInfF7EAMLk7RDBpQHgDdEolfPRtc57CTx7F68Ua0
### Get all schedule
GET http://localhost:3001/schedule
Cookie: accessToken={{token}}

###Get schedule by id
GET http://localhost:3001/schedule/1
Cookie: accessToken={{token}}


###Get schedule by date
GET http://localhost:3001/api/schedule?date=...
Cookie: accessToken={{token}}

###Get schedule between date
GET http://localhost:3001/schedule?from_date=...&to_date=...
Cookie: accessToken={{token}}


###Get schedule by task
GET http://localhost:3001/schedule?task_id=2
Cookie: accessToken={{token}}

### Create schedule
POST http://localhost:3001/schedule
Content-Type: application/json
Cookie: accessToken={{token}}

{
    "date": "2026-02-05",
    "start_time": "08:30:00",
    "end_time": "10:30:00",
    "task_name": "3123213213"
}


### Update schedule
PATCH http://localhost:3001/schedule/1
Content-Type: application/json
Cookie: accessToken={{token}}

{
    "date": "2026-02-05",
    "start_time": "10:30:00",
    "end_time": "16:30:00",
    "task_id": 2
}

