@baseUrl = http://localhost:3001
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImR1Y3RyaTA5ODFAZ21haWwuY29tIiwidXNlcl9pZCI6MywiaWF0IjoxNzcwMzc1MTUyLCJleHAiOjE3NzAzNzYwNTJ9.WnuL8EjQ-iXFpSyh1HZ6u2oRiV0fM3ksQoHbigp78hw
### Get all task
GET http://localhost:3001/task
Cookie: accessToken={{token}}

### Get task by id
GET http://localhost:3001/task/1
Cookie: accessToken={{token}}


### Get task history
GET http://localhost:3001/task/task_history
Cookie: accessToken={{token}}

###Post new task
POST http://localhost:3001/task
Content-Type: application/json
Cookie: accessToken={{token}}

{
    "name": "Học Node.js nâng cao",
    "description": "Tìm hiểu về Worker Threads và Streams",
    "deadline": "2026-02-10T23:59:59+07:00",
    "working_time": 150,
    "finished": false
}

###Update task
PATCH  http://localhost:3001/task/3
Content-Type: application/json
Cookie: accessToken={{token}}

{
    "name": "Học Reactjs cơ bản",
    "description": "Tìm hiểu về Worker Threads và Streams",
    "deadline": "2026-02-10T23:59:59+07:00",
    "working_time": 150,
    "finished": true
}

###Delete task
DELETE http://localhost:3001/task/1
Content-Type: application/json
Cookie: accessToken={{token}}