@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImR1Y3RyaTA5ODFAZ21haWwuY29tIiwidXNlcl9pZCI6MSwiaWF0IjoxNzcwNDQyMjM5LCJleHAiOjE3NzA0NDMxMzl9._zb2q-n2Eae3uXcaClgmOmWMdyGLZDBsyKh_Y5P9Cnw

###1. POST working-time
POST http://localhost:3002/working-time
Content-Type: application/json
Cookie: accessToken={{accessToken}}

{
    "name": "Viết báo cáo tháng",
    "description": "Tổng hợp dữ liệu từ các phòng ban và dự thảo báo cáo quý 1 cho giám đốc."
}

###2. Get schedule
GET http://localhost:3002/schedule
Content-Type: application/json
Cookie: accessToken={{accessToken}}
